/**
 * AI Web Design Cliché Detection Rules (25 Rules)
 * Source: ai_web_design_cliches.pdf
 *
 * Detects common AI-generated UI/UX anti-patterns in frontend code
 * and provides professional remediation guidance.
 */
import { Finding } from '@/data/schema';
import { CodeFile } from '../scanner-engine';
import { locateMatchLine } from './shared/locate';
interface ClicheRuleResult {
    findings: Finding[];
    logs: string[];
}
export function evaluateAiClicheRules(file: CodeFile, lines: string[], cleanContent: string, findingCounter: {
    count: number;
}): ClicheRuleResult {
    const findings: Finding[] = [];
    const logs: string[] = [];
    // Only evaluate frontend component files
    const isFrontend = file.path.endsWith('.tsx') || file.path.endsWith('.jsx') || file.path.endsWith('.html') || file.path.endsWith('.css');
    if (!isFrontend)
        return { findings, logs };
    const ts = new Date().toLocaleTimeString();
    // CLICHE-07: Fabricated Brand Logos (Nexora, Vertexa, Lumina)
    // A "Trusted by" / "As seen on" strip whose entries (within the next ~25 lines) are template placeholder companies.
    // Real names that merely resemble them (e.g. Lumina) are not listed.
    const placeholderBrandRe = /\b(?:Acme(?:\s*(?:Corp|Inc|Co)\.?)?|Nexora|Vertexa|Quantiq|TechCorp|CloudSoft|DataPulse|SynergyAI|CyberVault|Globex|Initech|Umbrella\s*Corp)\b/i;
    let fakeLogoLineIdx = -1;
    const trustedByIdx = lines.findIndex(l => /trusted by|as seen on/i.test(l));
    if (trustedByIdx !== -1) {
        for (let i = trustedByIdx; i < Math.min(lines.length, trustedByIdx + 25); i++) {
            if (placeholderBrandRe.test(lines[i])) { fakeLogoLineIdx = i; break; }
        }
    }
    if (fakeLogoLineIdx !== -1) {
        const matchLineIdx = fakeLogoLineIdx;
        const lineNum = matchLineIdx + 1;
        findings.push({
            id: `cliche-${Date.now()}-${findingCounter.count++}`,
            ruleId: 207,
            type: 'VIBEPOLISH',
            title: 'CLICHE-07: Fabricated Brand Logos (Fake Trust Proof)',
            severity: 'MEDIUM',
            category: 'AI Cliché & Trust',
            filePath: file.path,
            lineRange: `L${lineNum}`,
            snippet: lines[matchLineIdx] || '"Trusted by" Nexora, Vertexa, Lumina...',
            reproductionSteps: [
                `Scanned social proof section in ${file.path}:${lineNum}.`,
                'Detected fabricated brand names typically generated by AI — destroys user trust.'
            ],
            remediationPrompt: `Remove fake logos in ${file.path}. Only display real customer/partner logos or focus on product value instead.`,
            status: 'OPEN',
            owner: 'Marketing',
            falsePositive: false
        });
        logs.push(`[${ts}] 🎨 CLICHE-07: Fake trust logos detected (${file.path}:${lineNum})`);
    }
    // CLICHE-48: Unlabeled Toggle Switch Interactive Ambiguity
    // A self-closing <Switch /> (no text children) with no accessible name: no aria-label/aria-labelledby, no id for a
    // <Label htmlFor>, no spread props, not wrapped in a <label> and not inside a shadcn <FormControl> (which wires the label).
    let unlabeledSwitchIdx = -1;
    for (const m of cleanContent.matchAll(/<Switch\b((?:[^>]|=>)*?)\/>/g)) {
        const attrs = m[1];
        if (/aria-label|aria-labelledby|\bid\s*=|\{\s*\.\.\./.test(attrs)) continue;
        const before = cleanContent.slice(Math.max(0, (m.index ?? 0) - 300), m.index);
        const lowerBefore = before.toLowerCase();
        const lastLabelOpen = lowerBefore.lastIndexOf('<label');
        const insideLabel = lastLabelOpen !== -1 && lowerBefore.indexOf('</label>', lastLabelOpen) === -1;
        if (/<FormControl\b[^>]*>\s*$/.test(before) || insideLabel) continue;
        unlabeledSwitchIdx = cleanContent.slice(0, m.index).split('\n').length - 1;
        break;
    }
    if (unlabeledSwitchIdx !== -1) {
        const matchLineIdx = unlabeledSwitchIdx;
        const lineNum = matchLineIdx + 1;
        findings.push({
            id: `cliche-${Date.now()}-${findingCounter.count++}`,
            ruleId: 248,
            type: 'VIBEPOLISH',
            title: 'CLICHE-48: Unlabeled Toggle Switch Interactive Ambiguity',
            severity: 'LOW',
            category: "AI Clich\u00e9 & Accessibility",
            filePath: file.path,
            lineRange: `L${lineNum}`,
            snippet: lines[matchLineIdx] || '<detected cliche pattern>',
            reproductionSteps: [
                `Scanned UI layout and design tokens in ${file.path}:${lineNum}.`,
                "Detected unlabeled toggle switch component: Toggle switch component rendering without associated label or active status indicator"
            ],
            remediationPrompt: "Pair every toggle with an explicit textual state label and aria-checked binding.",
            status: 'OPEN',
            owner: 'UI Architect',
            falsePositive: false
        });
        logs.push(`[${ts}] 🎨 CLICHE-48: Unlabeled Toggle Switch Interactive Ambiguity detected (${file.path}:${lineNum})`);
    }
    // CLICHE-50: Orphaned Dead Social Media Footer Anchors
    if (/href=["\']https?:\/\/(?:twitter|x|facebook|instagram)\.com\/?["\']/i.test(cleanContent)) {
        const matchLineIdx = locateMatchLine(lines, [/href=["\']https?:\/\/(?:twitter|x|facebook|instagram)\.com\/?["\']/i], l => !l.trim().startsWith('//') && !l.trim().startsWith('*'));
        const lineNum = matchLineIdx !== -1 ? matchLineIdx + 1 : 1;
        findings.push({
            id: `cliche-${Date.now()}-${findingCounter.count++}`,
            ruleId: 250,
            type: 'VIBEPOLISH',
            title: 'CLICHE-50: Orphaned Dead Social Media Footer Anchors',
            severity: 'LOW',
            category: "AI Clich\u00e9 & Navigation",
            filePath: file.path,
            lineRange: `L${lineNum}`,
            snippet: lines[matchLineIdx] || '<detected cliche pattern>',
            reproductionSteps: [
                `Scanned UI layout and design tokens in ${file.path}:${lineNum}.`,
                "Detected orphaned dead social media root link in footer: Twitter, Facebook, Instagram icons linking to root domains without company handle"
            ],
            remediationPrompt: "Link only to verified, active corporate channels or omit unused platforms completely.",
            status: 'OPEN',
            owner: 'UI Architect',
            falsePositive: false
        });
        logs.push(`[${ts}] 🎨 CLICHE-50: Orphaned Dead Social Media Footer Anchors detected (${file.path}:${lineNum})`);
    }
    // CLICHE-74: Unannounced External Link Navigation
    // An <a> opening an absolute external URL in a new tab with no rel at all (rel may come before or after target).
    let blankNoRelIdx = -1;
    for (const m of cleanContent.matchAll(/<a\b((?:[^>]|=>)*)>/g)) {
        const attrs = m[1];
        if (!/\btarget\s*=\s*(?:["']_blank["']|\{\s*["']_blank["']\s*\})/.test(attrs)) continue;
        if (!/\bhref\s*=\s*\{?\s*["'`]https?:\/\//.test(attrs)) continue;
        if (/\brel\s*=|\{\s*\.\.\./.test(attrs)) continue;
        blankNoRelIdx = cleanContent.slice(0, m.index).split('\n').length - 1;
        break;
    }
    if (blankNoRelIdx !== -1) {
        const matchLineIdx = blankNoRelIdx;
        const lineNum = matchLineIdx + 1;
        findings.push({
            id: `cliche-${Date.now()}-${findingCounter.count++}`,
            ruleId: 274,
            type: 'VIBEPOLISH',
            title: 'CLICHE-74: Unannounced External Link Navigation',
            severity: 'LOW',
            category: "AI Clich\u00e9 & Accessibility",
            filePath: file.path,
            lineRange: `L${lineNum}`,
            snippet: lines[matchLineIdx] || '<detected cliche pattern>',
            reproductionSteps: [
                `Scanned UI layout and design tokens in ${file.path}:${lineNum}.`,
                "Detected an external link opened with target=\"_blank\" and no rel attribute (window.opener / Referer leak in older browsers; react/jsx-no-target-blank)."
            ],
            remediationPrompt: "Add rel=\"noopener noreferrer\" to links opened with target=\"_blank\", and mark them as opening a new tab (icon plus screen-reader text).",
            status: 'OPEN',
            owner: 'UI Architect',
            falsePositive: false
        });
        logs.push(`[${ts}] 🎨 CLICHE-74: Unannounced External Link Navigation detected (${file.path}:${lineNum})`);
    }
    return { findings, logs };
}
