import { Finding } from '@/data/schema';
import { CodeFile } from '../scanner-engine';
export interface CommentRuleResult {
    findings: Finding[];
    logs: string[];
}
/**
 * Evaluates raw un-stripped source code comments for AI generation artifacts,
 * pasted prompt residue and unresolved placeholder comments.
 * Removed as unsound: 27222 (matched a hard-coded list of this product's own section labels).
 * Runs BEFORE stripComments() is applied.
 */
export function evaluateAiCommentRules(file: CodeFile, lines: string[], rawContent: string, findingCounter: {
    count: number;
}): CommentRuleResult {
    const findings: Finding[] = [];
    const logs: string[] = [];
    const lowerPath = file.path.toLowerCase().replace(/\\/g, '/');
    // Skip documentation, markdown, catalogs, mocks, and agent instructions
    if (lowerPath.includes('docs/') || lowerPath.endsWith('.md') || lowerPath.endsWith('.d.ts')) {
        return { findings, logs };
    }
    const ts = new Date().toLocaleTimeString();
    // CLICHE-AI-COMMENT-01: Synthetic LLM Prompt Artifacts & Header Injections
    // Pasted chat-transcript residue only: "generated by <assistant>", "model output:", "LLM response:".
    const syntheticPromptRegex = /(?:\bgenerated (?:by|with|using) (?:github copilot|copilot|chatgpt|gpt-4o?|v0|claude|cursor)\b|\bmodel output\s*:|\bllm response\s*:)/i;
    // CLICHE-AI-COMMENT-03: Unresolved AI Placeholder / Incomplete Code Comments
    const unresolvedPlaceholderRegex = /\/\/\s*(?:TODO:\s*(?:implement|add real|replace with)|placeholder for production|mock implementation for now)/i;
    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        const lineNum = i + 1;
        const trimmed = line.trim();
        const isCommentLine = trimmed.startsWith('//') || trimmed.startsWith('/*') || trimmed.startsWith('*') || trimmed.startsWith('{/*');
        if (!isCommentLine)
            continue;
        // Check 1: Synthetic Prompt Artifacts
        if (syntheticPromptRegex.test(line)) {
            findings.push({
                id: `ai-comment-${Date.now()}-${findingCounter.count++}`,
                ruleId: 27221,
                type: 'VIBEPOLISH',
                title: 'CLICHE-AI-COMMENT-01: Synthetic LLM Prompt Artifact & Header Injection',
                severity: 'LOW',
                category: 'AI Cliché & Code Hygiene',
                filePath: file.path,
                lineRange: `L${lineNum}`,
                snippet: line.trim(),
                reproductionSteps: [
                    `Scanned raw source code comments in ${file.path}:${lineNum}.`,
                    `Detected synthetic LLM prompt residue or hallucinated header artifact: "${line.trim()}"`
                ],
                remediationPrompt: `Remove synthetic LLM prompt residue from ${file.path}. Production code should not contain LLM prompt artifacts or boilerplate comment headers.`,
                status: 'OPEN',
                owner: 'Lead Engineer',
                falsePositive: false
            });
            logs.push(`[${ts}] 🤖 CLICHE-AI-COMMENT-01: Synthetic prompt artifact detected (${file.path}:${lineNum})`);
        }
        // Check 3: Unresolved AI Placeholders
        if (unresolvedPlaceholderRegex.test(line)) {
            findings.push({
                id: `ai-comment-${Date.now()}-${findingCounter.count++}`,
                ruleId: 27223,
                type: 'VIBEPOLISH',
                title: 'CLICHE-AI-COMMENT-03: Unresolved AI Placeholder / Incomplete Code Comment',
                severity: 'MEDIUM',
                category: 'Code Quality & Completeness',
                filePath: file.path,
                lineRange: `L${lineNum}`,
                snippet: line.trim(),
                reproductionSteps: [
                    `Scanned source code comments in ${file.path}:${lineNum}.`,
                    `Detected unresolved AI placeholder: "${line.trim()}".`
                ],
                remediationPrompt: `Implement production-grade logic for ${file.path} and remove placeholder comments before release clearance.`,
                status: 'OPEN',
                owner: 'Engineering Lead',
                falsePositive: false
            });
            logs.push(`[${ts}] ⚠️ CLICHE-AI-COMMENT-03: Unresolved AI placeholder detected (${file.path}:${lineNum})`);
        }
    }
    return { findings, logs };
}
