import { Finding } from '@/data/schema';
import { CodeFile } from '../scanner-engine';
export interface CommentRuleResult {
    findings: Finding[];
    logs: string[];
}
/**
 * Evaluates raw un-stripped source code comments for AI generation artifacts,
 * repetitive prompt residues, and hallucinated section markers.
 * Runs BEFORE stripComments() is applied.
 */
export function evaluateAiCommentRules(file: CodeFile, lines: string[], rawContent: string, findingCounter: {
    count: number;
}): CommentRuleResult {
    const findings: Finding[] = [];
    const logs: string[] = [];
    const lowerPath = file.path.toLowerCase().replace(/\\/g, '/');
    // Skip documentation, markdown, catalogs, mocks, and agent instructions
    if (lowerPath.includes('docs/') || lowerPath.endsWith('.md') || lowerPath.endsWith('.d.ts')) {
        return { findings, logs };
    }
    const ts = new Date().toLocaleTimeString();
    // CLICHE-AI-COMMENT-01: Synthetic LLM Prompt Artifacts & Header Injections
    const syntheticPromptRegex = /(?:i18n useTranslation enabled|keyboard accessibility handler|prompt:\s*|generated by (?:copilot|chatgpt|v0|claude)|model output:|llm response:)/i;
    // CLICHE-AI-COMMENT-02: Hallucinated / Artificial Section Marker Comments in JSX
    const artificialSectionRegex = /\{\/\*\s*(?:Release Clearance Badge|Commanding Editorial Headline|Subtitle Value Proposition|Trust Stats Counter Bar|Primary Navigation Shell|Interactive Terminal Playground Wrapper|Feature Grid Section|Call to Action Container|Card Component Wrapper|Hero Section Badge|Quick Repository Input)\s*\*\/\}/i;
    // CLICHE-AI-COMMENT-03: Unresolved AI Placeholder / Incomplete Code Comments
    const unresolvedPlaceholderRegex = /\/\/\s*(?:TODO:\s*(?:implement|add real|replace with)|placeholder for production|mock implementation for now)/i;
    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        const lineNum = i + 1;
        const trimmed = line.trim();
        const isCommentLine = trimmed.startsWith('//') || trimmed.startsWith('/*') || trimmed.startsWith('*') || trimmed.startsWith('{/*');
        if (!isCommentLine)
            continue;
        // Check 1: Synthetic Prompt Artifacts
        if (syntheticPromptRegex.test(line)) {
            findings.push({
                id: `ai-comment-${Date.now()}-${findingCounter.count++}`,
                ruleId: 231,
                type: 'VIBEPOLISH',
                title: 'CLICHE-AI-COMMENT-01: Synthetic LLM Prompt Artifact & Header Injection',
                severity: 'HIGH',
                category: 'AI Cliché & Code Hygiene',
                filePath: file.path,
                lineRange: `L${lineNum}`,
                snippet: line.trim(),
                reproductionSteps: [
                    `Scanned raw source code comments in ${file.path}:${lineNum}.`,
                    `Detected synthetic LLM prompt residue or hallucinated header artifact: "${line.trim()}"`
                ],
                remediationPrompt: `Remove synthetic LLM prompt residue from ${file.path}. Production code should not contain LLM prompt artifacts or boilerplate comment headers.`,
                status: 'OPEN',
                owner: 'Lead Engineer',
                falsePositive: false
            });
            logs.push(`[${ts}] 🤖 CLICHE-AI-COMMENT-01: Synthetic prompt artifact detected (${file.path}:${lineNum})`);
        }
        // Check 2: Artificial Section Marker Comments
        if (artificialSectionRegex.test(line)) {
            findings.push({
                id: `ai-comment-${Date.now()}-${findingCounter.count++}`,
                ruleId: 232,
                type: 'VIBEPOLISH',
                title: 'CLICHE-AI-COMMENT-02: Artificial LLM Section Marker Comment in JSX',
                severity: 'MEDIUM',
                category: 'AI Cliché & Layout',
                filePath: file.path,
                lineRange: `L${lineNum}`,
                snippet: line.trim(),
                reproductionSteps: [
                    `Scanned raw JSX comments in ${file.path}:${lineNum}.`,
                    `Detected boilerplate AI section label: "${line.trim()}".`
                ],
                remediationPrompt: `Remove artificial section marker comments in ${file.path}. Use clean, semantic component structure rather than AI prompt section labels.`,
                status: 'OPEN',
                owner: 'Frontend Architect',
                falsePositive: false
            });
            logs.push(`[${ts}] 🤖 CLICHE-AI-COMMENT-02: Artificial section marker detected (${file.path}:${lineNum})`);
        }
        // Check 3: Unresolved AI Placeholders
        if (unresolvedPlaceholderRegex.test(line)) {
            findings.push({
                id: `ai-comment-${Date.now()}-${findingCounter.count++}`,
                ruleId: 233,
                type: 'VIBEPOLISH',
                title: 'CLICHE-AI-COMMENT-03: Unresolved AI Placeholder / Incomplete Code Comment',
                severity: 'MEDIUM',
                category: 'Code Quality & Completeness',
                filePath: file.path,
                lineRange: `L${lineNum}`,
                snippet: line.trim(),
                reproductionSteps: [
                    `Scanned source code comments in ${file.path}:${lineNum}.`,
                    `Detected unresolved AI placeholder: "${line.trim()}".`
                ],
                remediationPrompt: `Implement production-grade logic for ${file.path} and remove placeholder comments before release clearance.`,
                status: 'OPEN',
                owner: 'Engineering Lead',
                falsePositive: false
            });
            logs.push(`[${ts}] ⚠️ CLICHE-AI-COMMENT-03: Unresolved AI placeholder detected (${file.path}:${lineNum})`);
        }
    }
    return { findings, logs };
}
